from svd_sparse_cf import SVDSparseCollaborativeFilteringRecommender
from io import StringIO
import numpy as np


user = [
    {"user_id": "_BcWyKQL16ndpBdggh2kNA", "name": "Karen", "review_count": 4274, "yelping_since": "2008-05-29 12:29:54", "useful": 16950, "funny": 5203, "cool": 9759, "elite": "2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,20,20,2021", "fans": 558, "average_stars": 3.69, "compliment_hot": 357, "compliment_more": 59, "compliment_profile": 42, "compliment_cute": 15, "compliment_list": 35, "compliment_note": 262, "compliment_plain": 498, "compliment_cool": 394, "compliment_funny": 394, "compliment_writer": 191, "compliment_photos": 36},
    {"user_id": "pou3BbKsIozfH50rxmnMew", "name": "Brett", "review_count": 2812, "yelping_since": "2012-01-11 17:19:55", "useful": 22586, "funny": 8950, "cool": 14927, "elite": "2012,2013,2014,2015,2016,2017,2018,2019,20,20,2021", "fans": 914, "average_stars": 4.28, "compliment_hot": 404, "compliment_more": 96, "compliment_profile": 44, "compliment_cute": 12, "compliment_list": 28, "compliment_note": 1131, "compliment_plain": 3667, "compliment_cool": 1265, "compliment_funny": 1265, "compliment_writer": 529, "compliment_photos": 398},
    {"user_id": "IKbjLnfBQtEyVzEu8CuOLg", "name": "Erica", "review_count": 800, "yelping_since": "2010-01-02 04:59:57", "useful": 1571, "funny": 290, "cool": 671, "elite": "2012,2013,2014,2015,2016,2017,2019", "fans": 64, "average_stars": 3.87, "compliment_hot": 37, "compliment_more": 7, "compliment_profile": 1, "compliment_cute": 2, "compliment_list": 0, "compliment_note": 30, "compliment_plain": 67, "compliment_cool": 57, "compliment_funny": 57, "compliment_writer": 47, "compliment_photos": 1},
    {"user_id": "-kLVfaJytOJY2-QdQoCcNQ", "name": "Christina", "review_count": 1454, "yelping_since": "2012-10-08 01:25:31", "useful": 10382, "funny": 2760, "cool": 6559, "elite": "2013,2014,2015,2016,2017,2018,2019,20,20,2021", "fans": 669, "average_stars": 4.21, "compliment_hot": 93, "compliment_more": 9, "compliment_profile": 6, "compliment_cute": 4, "compliment_list": 0, "compliment_note": 178, "compliment_plain": 972, "compliment_cool": 233, "compliment_funny": 233, "compliment_writer": 126, "compliment_photos": 266},
    {"user_id": "ET8n-r7glWYqZhuR6GcdNw", "name": "Michelle", "review_count": 2256, "yelping_since": "2008-03-28 13:26:38", "useful": 28235, "funny": 8198, "cool": 18687, "elite": "2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,20,20,2021", "fans": 1353, "average_stars": 4.05, "compliment_hot": 1594, "compliment_more": 143, "compliment_profile": 175, "compliment_cute": 207, "compliment_list": 112, "compliment_note": 1576, "compliment_plain": 6561, "compliment_cool": 2349, "compliment_funny": 2349, "compliment_writer": 526, "compliment_photos": 449},
]

business = [
    {"business_id": "EtKSTHV5Qx_Q7Aur9o4kQQ", "name": "Village Whiskey", "address": "118 S 20th St", "city": "Philadelphia", "state": "PA", "postal_code": "19103", "latitude": 39.9514165949, "longitude": -75.1737677917, "stars": 4.0, "review_count": 1553, "is_open": 1, "attributes": {"RestaurantsReservations": "False", "RestaurantsGoodForGroups": "False", "NoiseLevel": "u'average'", "RestaurantsPriceRange2": "2", "RestaurantsAttire": "u'casual'", "GoodForKids": "False", "BusinessAcceptsCreditCards": "True", "Alcohol": "u'full_bar'", "HasTV": "False", "WiFi": "u'no'", "BusinessParking": "{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': False}", "BikeParking": "True", "RestaurantsDelivery": "True", "OutdoorSeating": "True", "Caters": "True", "Music": "{'dj': False, 'background_music': False, 'no_music': False, 'jukebox': False, 'live': False, 'video': False, 'karaoke': False}", "Smoking": "u'no'", "ByAppointmentOnly": "False", "CoatCheck": "False", "GoodForMeal": "{u'breakfast': False, u'brunch': False, u'lunch': None, u'dinner': True, u'latenight': None, u'dessert': False}", "HappyHour": "True", "RestaurantsTakeOut": "True", "DriveThru": "False", "RestaurantsTableService": "True", "Ambience": "{'touristy': False, 'hipster': False, 'romantic': False, 'divey': False, 'intimate': False, 'trendy': True, 'upscale': False, 'classy': True, 'casual': False}", "BestNights": "{'monday': False, 'tuesday': True, 'friday': True, 'wednesday': True, 'thursday': False, 'sunday': False, 'saturday': False}", "GoodForDancing": "False", "WheelchairAccessible": "True", "DogsAllowed": "False"}, "categories": "Bars, Nightlife, Whiskey Bars, Burgers, Restaurants, American (New)", "hours": {"Wednesday": "16:0-21:0", "Thursday": "16:0-21:0", "Friday": "16:0-22:0", "Saturday": "12:0-22:0", "Sunday": "12:0-21:0"}},
    {"business_id": "L5U9dBXYKNDyWp4lk9j9QQ", "name": "Iron Hill Brewery & Restaurant", "address": "30 East State St", "city": "Media", "state": "PA", "postal_code": "19063", "latitude": 39.9175793684, "longitude": -75.388318839, "stars": 3.5, "review_count": 427, "is_open": 1, "attributes": {"Ambience": "{'romantic': False, 'intimate': False, 'touristy': False, 'hipster': False, 'divey': False, 'classy': False, 'trendy': False, 'upscale': False, 'casual': True}", "WiFi": "'free'", "RestaurantsGoodForGroups": "True", "RestaurantsReservations": "True", "BikeParking": "True", "BusinessAcceptsCreditCards": "True", "RestaurantsAttire": "'casual'", "RestaurantsPriceRange2": "2", "RestaurantsTakeOut": "True", "OutdoorSeating": "True", "Alcohol": "u'full_bar'", "HasTV": "True", "GoodForKids": "True", "HappyHour": "True", "Caters": "True", "RestaurantsDelivery": "True", "BusinessParking": "{'garage': False, 'street': True, 'validated': False, 'lot': True, 'valet': False}", "GoodForMeal": "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': True, 'brunch': False, 'breakfast': False}", "DogsAllowed": "False", "NoiseLevel": "u'loud'", "RestaurantsTableService": "True"}, "categories": "Restaurants, American (New), Food, Breweries", "hours": {"Monday": "12:0-21:30", "Tuesday": "12:0-21:30", "Wednesday": "12:0-21:30", "Thursday": "12:0-21:30", "Friday": "12:0-22:0", "Saturday": "12:0-22:0", "Sunday": "12:0-21:30"}},
    {"business_id": "FqOCC8Y9xryaX7sIBJcrxA", "name": "Vic Sushi Bar", "address": "2035 Sansom St", "city": "Philadelphia", "state": "PA", "postal_code": "19103", "latitude": 39.9515773, "longitude": -75.174834, "stars": 4.0, "review_count": 884, "is_open": 1, "attributes": {"HasTV": "False", "RestaurantsDelivery": "True", "BikeParking": "True", "RestaurantsGoodForGroups": "False", "RestaurantsReservations": "False", "Caters": "False", "RestaurantsPriceRange2": "2", "BusinessParking": "{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': False}", "RestaurantsAttire": "'casual'", "Corkage": "False", "NoiseLevel": "u'average'", "GoodForKids": "False", "BusinessAcceptsCreditCards": "True", "BYOBCorkage": "'yes_free'", "Alcohol": "'none'", "WiFi": "u'no'", "GoodForMeal": "{'dessert': False, 'latenight': False, 'lunch': True, 'dinner': True, 'brunch': False, 'breakfast': False}", "DogsAllowed": "False", "HappyHour": "False", "OutdoorSeating": "None", "ByAppointmentOnly": "False", "Ambience": "{'touristy': False, 'hipster': False, 'romantic': False, 'divey': False, 'intimate': False, 'trendy': False, 'upscale': False, 'classy': True, 'casual': True}", "RestaurantsTakeOut": "None"}, "categories": "Japanese, Sushi Bars, Restaurants", "hours": {"Monday": "11:30-21:30", "Tuesday": "11:30-21:30", "Wednesday": "11:30-21:30", "Thursday": "11:30-21:30", "Friday": "11:30-22:0", "Saturday": "12:0-22:0"}},
    {"business_id": "BnprLJ4Lr33--YjTmgk9Zg", "name": "Doma", "address": "1822 Callowhill St", "city": "Philadelphia", "state": "PA", "postal_code": "19130", "latitude": 39.9602728, "longitude": -75.1692394, "stars": 4.0, "review_count": 457, "is_open": 1, "attributes": {"Alcohol": "u'none'", "RestaurantsDelivery": "True", "RestaurantsGoodForGroups": "False", "RestaurantsReservations": "True", "BusinessParking": "{'garage': False, 'street': True, 'validated': False, 'lot': False, 'valet': False}", "BusinessAcceptsCreditCards": "True", "RestaurantsTakeOut": "True", "OutdoorSeating": "True", "Caters": "True", "HasTV": "False", "GoodForKids": "False", "WiFi": "u'no'", "RestaurantsAttire": "u'casual'", "RestaurantsPriceRange2": "2", "NoiseLevel": "u'average'", "BikeParking": "True", "Corkage": "False", "BYOB": "True", "RestaurantsTableService": "True", "WheelchairAccessible": "True", "Ambience": "{'touristy': False, 'hipster': False, 'romantic': False, 'divey': False, 'intimate': False, 'trendy': True, 'upscale': False, 'classy': True, 'casual': False}", "GoodForMeal": "{'dessert': False, 'latenight': False, 'lunch': None, 'dinner': True, 'brunch': False, 'breakfast': False}"}, "categories": "Restaurants, Korean, Japanese, Sushi Bars", "hours": {"Monday": "0:0-0:0", "Tuesday": "16:0-21:0", "Wednesday": "16:0-21:0", "Thursday": "16:0-21:0", "Friday": "16:0-21:30", "Saturday": "16:0-21:30", "Sunday": "16:0-21:0"}},
    {"business_id": "hExi86DTBlmIhB2FLvqrHg", "name": "On Swann", "address": "1501 W Swann Ave", "city": "Tampa", "state": "FL", "postal_code": "33606", "latitude": 27.9374616, "longitude": -82.4751492, "stars": 4.5, "review_count": 1291, "is_open": 1, "attributes": {"ByAppointmentOnly": "False", "Caters": "False", "HappyHour": "False", "RestaurantsPriceRange2": "2", "Alcohol": "u'full_bar'", "BikeParking": "False", "HasTV": "False", "DriveThru": "False", "CoatCheck": "False", "BusinessAcceptsCreditCards": "True", "BusinessAcceptsBitcoin": "False", "RestaurantsReservations": "True", "RestaurantsDelivery": "False", "NoiseLevel": "u'loud'", "DogsAllowed": "True", "RestaurantsAttire": "'casual'", "Smoking": "u'no'", "GoodForDancing": "False", "WheelchairAccessible": "True", "GoodForKids": "True", "Corkage": "True", "WiFi": "u'free'", "RestaurantsTableService": "True", "Music": "{'dj': False, 'background_music': False, 'no_music': False, 'jukebox': False, 'live': False, 'video': False, 'karaoke': False}", "BusinessParking": "{'garage': True, 'street': True, 'validated': False, 'lot': False, 'valet': True}", "OutdoorSeating": "True", "BestNights": "{'monday': False, 'tuesday': True, 'friday': True, 'wednesday': False, 'thursday': False, 'sunday': False, 'saturday': True}", "Ambience": "{u'divey': False, u'hipster': None, u'casual': None, u'touristy': False, u'trendy': True, u'intimate': None, u'romantic': None, u'classy': True, u'upscale': None}", "BYOB": "True", "GoodForMeal": "{u'breakfast': False, u'brunch': None, u'lunch': True, u'dinner': True, u'latenight': False, u'dessert': None}", "RestaurantsGoodForGroups": "True", "RestaurantsTakeOut": "False"}, "categories": "Desserts, Restaurants, Bars, Nightlife, American (New), Food", "hours": {"Monday": "0:0-0:0", "Tuesday": "11:0-19:0", "Wednesday": "17:0-22:0", "Thursday": "11:0-19:0", "Friday": "17:0-23:0", "Saturday": "17:0-23:0", "Sunday": "11:0-22:0"}},
]

review = [
    {"review_id": "RRRFmjxcJ54Euxgi0zpL3Q", "user_id": "_BcWyKQL16ndpBdggh2kNA", "business_id": "BnprLJ4Lr33--YjTmgk9Zg", "stars": 5.0, "useful": 4, "funny": 1, "cool": 3, "text": "Since my last update, we have been to Doma 3 or 4 times including New Year's Eve (amazing) and last night just me and my 6 year old.\n\nShe ate 2 orders of Shrimp Shumai. and a bunch of edamame.\nAnd then she said, \"Mommy, I don;t want any chocolate lava cake this time\".\n\nSmart kid.\n\nI had the Naked Salmon roll (sans jalapenos) and it was so good, I ordered a second one.\n\nAnd that was it.\n\n2 rounds of Shumai 'n salmon.\n\nAnd we were stuffed.\n\nDan & the guys are so great with my little one.  She loves to sit at the high-top tables in the back.  (I prefer the regular tables, but I was out voted.)\n\nOh - and if you go to DOMA - save room for dessert (if you can).  The mochi-coated strawberries dipped in fudge and chocolate lava cake (sounds trite - but they make a good one) are amazing.", "date": "2011-02-17 15:21:49"},
    {"review_id": "73Zl5Ys314FIbQIVtzn9Ow", "user_id": "_BcWyKQL16ndpBdggh2kNA", "business_id": "L5U9dBXYKNDyWp4lk9j9QQ", "stars": 4.0, "useful": 1, "funny": 0, "cool": 2, "text": "Pleasantly surprisedby the quality of the food.  Small Plate option of a single Salmon Spring Roll ($5.50) was perfect.  Quinoa Salad was nice but thank goodness I got the cloyingly sweet dressing on the side.  Loaded with sugary fruit puree too.\n\nIt's close by - so we'll be back.", "date": "2012-06-23 01:22:04"},
    {"review_id": "yfM3X7NCocnIIjuZVRhkyA", "user_id": "_BcWyKQL16ndpBdggh2kNA", "business_id": "BnprLJ4Lr33--YjTmgk9Zg", "stars": 5.0, "useful": 3, "funny": 0, "cool": 2, "text": "Doma!!!!\nWhat a treat to be able to dine here again.\n\nTonight re-affirmed that Doma is one of the best restaurants in the city.\nIt's my fave and my 9 year kid (who has been coming here since age 3 or 4) loves it too and scarfs down salmon sushi, edamame and her favorite - BIG shrimp shumai.\n\nI had a delectable Kalbi dinner with 9 large pieces of tender, juicy short-ribs.\nDH had a variety of sushi including our love - the Naked Salmon.  (try this!!)\n\nThank you DOMA (and Pat and staff) for wonderful food and service for all these years - and hopefully many more.\n\nWe love you!! (And we miss you - now that we are out in the 'burbs.)", "date": "2013-11-17 01:21:19"},
    {"review_id": "x7MaR882s8z-lDAokf6pHw", "user_id": "ET8n-r7glWYqZhuR6GcdNw", "business_id": "EtKSTHV5Qx_Q7Aur9o4kQQ", "stars": 4.0, "useful": 45, "funny": 31, "cool": 22, "text": "I finally had a burger at Village Whiskey. \n\nIt was delicious. It was super expensive. I may have to keep a piggy bank to save specifically for my next lunch there. Allow me to elaborate: \n\nVillage Burger [served on a sesame bun with lettuce, tomato and homemade Russian dressing (on the side for me) and a pickle] - $11\nadd Jasper Hill cheddar - $3.5\nadd smoked bacon - $2.5\nadd pickled long hots - $3 \nadd about ten miles on the treadmill - (free, with membership)\n\nMy burger quickly amounted to a whopping twenty dollars, and that was before adding on an order of duck fat fries with Sly Fox cheddar sauce on the side, shared with my dining companion. The meal, naturally, was over-indulgent and delicious. \n\nLunch at Village Whiskey is definitely a splurge, not a once-a-week occurrence. Service is top-notch all around, and you'll feel like a baller with an expense account for an hour or so. You may even rub elbows with the likes of Gary Matthews at the bar, as we did the day of our visit.\n\nPro tip: All the single ladies should head on over around lunch time during the work week. The male:female ratio is approximately 10:1.", "date": "2011-04-06 13:59:39"},
    {"review_id": "o5AB7GouW8QSWbVIuNex_A", "user_id": "IKbjLnfBQtEyVzEu8CuOLg", "business_id": "hExi86DTBlmIhB2FLvqrHg", "stars": 5.0, "useful": 2, "funny": 0, "cool": 2, "text": "I was graciously invited to return to On Swann for a meal on the house, which was very much appreciated. This meal was truly wonderful - the food, the service, the experience, all top notch. Victor was our server for this visit and he was excellent (along with the manager whose name escapes me and business partner/owner Chris). Victor knew the menu front to back, and was very helpful in making our selections. And our favorite server Gary even came out to say hi, which was very nice. Every dish was delicious...we had the marinated octopus special, bacon wrapped dates special, zeppoles with ricotta corn dip, cauliflower, short rib pasta, cobia, and pana cotta. Our favorites were the cauliflower and cobia, but every dish was truly delicious. We are so appreciative that we got to return to On Swann and see all the restaurant has to offer. We will certainly be back in the near future.", "date": "2017-02-27 16:09:10"},
]


def test_save_n_load_identity():
    model_save = SVDSparseCollaborativeFilteringRecommender(user, business, review, 2)
    model_save.fit()
    saved_file = StringIO()
    model_save.save(saved_file)
    saved_file.seek(0)

    model_load = SVDSparseCollaborativeFilteringRecommender(user, business, review, 2)
    model_load.load(saved_file)
    assert np.allclose(model_save.model.u, model_load.model.u)
    assert np.allclose(model_save.model.s, model_load.model.s)
    assert np.allclose(model_save.model.vt, model_load.model.vt)

